version: 2.0

jobs:
  build_gcc:
    docker:
      - image: cadenzio/cpp-build:0.0.3
    steps:
      - checkout
      - run: 
          name: Submodule Checkout
          command: git submodule sync && git submodule update --init
      - run:
          name: CMake
          command: cmake . -DCMAKE_BUILD_TYPE=Debug -G Ninja
      - run:
          name: Build
          command: ninja
      - run:
          name: Unit Test
          command: python3 dependencies/mettle/scripts/mettle_junit.py bin/ut.* --output artifacts/test_results
      - run:
          name: Generate Test Report
          command: /allure-2.6.0/bin/allure generate artifacts/test_results -o artifacts/test_reports
      - store_artifacts:
          path: artifacts
      - store_test_results:
          path: artifacts
  build_clang:
    docker:
      - image: cadenzio/cpp-build:0.0.3
    steps:
      - checkout
      - run: 
          name: Submodule Checkout
          command: git submodule sync && git submodule update --init
      - run:
          name: CMake
          command: cmake . -DCMAKE_BUILD_TYPE=Release -G Ninja
          environment:
            CXX: clang++-6.0
            CC: clang-6.0
      - run:
          name: Build
          command: ninja
      - run:
          name: Unit Test
          command: python3 dependencies/mettle/scripts/mettle_junit.py bin/ut.* --output artifacts/test_results
      - run:
          name: Generate Test Report
          command: /allure-2.6.0/bin/allure generate artifacts/test_results -o artifacts/test_reports
      - store_artifacts:
          path: artifacts
      - store_test_results:
          path: artifacts
      - run: LLVM_PROFILE_FILE="value.profraw" bin/ut.value --no-subproc
      - run: LLVM_PROFILE_FILE="pitch.profraw" bin/ut.pitch --no-subproc
      - run: llvm-profdata merge -sparse value.profraw pitch.profraw -o stan.profdata
      - run: llvm-cov show src/libstan.so -instr-profile=stan.profdata > coverage.stan.txt 
      - run: 
          name: Upload Coverage Report
          command: bash <(curl -s https://codecov.io/bash) -t be1c64b9-e403-48b6-82ff-c2541e90e7c8
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc
      - build_clang
